# Практическая работа №1: Знакомство с языком R

## Задание №1
В данных заданиях **запрещено использовать циклы!**

1. Даны целые числа `n` и `sz`, создайте вектор из повторяющихся чисел от 1 до `n` размера `sz`. e.g.: `n = 3`, `sz = 10` должно вернуть `c(1, 2, 3, 1, 2, 3, 1, 2, 3, 1)`.

In [1]:
task1_1 <- function(n, sz) {
    rep(1:n, length.out = sz)
}

In [3]:
task1_1(3, 10)   # 1 2 3 1 2 3 1 2 3 1
task1_1(1, 5)    # 1 1 1 1 1
task1_1(5, 5)    # 1 2 3 4 5
task1_1(2, 6)    # 1 2 1 2 1 2

 [1] 1 2 3 1 2 3 1 2 3 1

[1] 1 1 1 1 1

[1] 1 2 3 4 5

[1] 1 2 1 2 1 2

2. Даны целые числа `n` и `sz`. Сгенерируйте вектор из случайных целых чисел от 1 до `n` и верните его. Выведите на экран, сколько раз сгенирировалась какое число.

In [ ]:
task1_2 <- function(n, sz) {
    v <- sample(1:n, sz, replace = TRUE)
    print(table(v))
    v
}

In [8]:
set.seed(42)
task1_2(5, 20)
task1_2(3, 30)

v
1 2 3 4 5
7 5 2 4 2

 [1] 1 5 1 1 2 4 2 2 1 4 1 5 4 2 2 3 1 1 3 4

v
 1  2  3
 8 15  7

 [1] 1 3 1 1 2 3 2 1 2 2 3 3 2 2 2 2 1 1 2 2 3 3 1 1 2 2 2 2 2 3

3. Дан вектор `x` и число `k`. Удалите из вектора все вхождения этого числа.

In [10]:
task1_3 <- function(x, k) {
    x[x != k]
}

In [ ]:
task1_3(c(1, 2, 3, 2, 4), 2)   # 1 3 4
task1_3(c(1, 2, 3), 9)         # 1 2 3
task1_3(c(5, 5, 5), 5)         # ничего
task1_3(c(1, 1, 2, 1, 3), 1)   # 2 3

[1] 1 3 4

[1] 1 2 3

numeric(0)

[1] 2 3

4. Дано целое число `steps`, сгенерируйте вектор длины `steps` состоящий из чисел 1 и -1. Верните вектор и сумму чисел.

In [12]:
task1_4 <- function(steps) {
    v <- sample(c(-1, 1), steps, replace = TRUE)
    list(vector = v, sum = sum(v))
}

In [31]:
set.seed(42)
task1_4(0)
task1_4(1)
task1_4(5)
task1_4(10)

$vector
numeric(0)

$sum
[1] 0

$vector
[1] -1

$sum
[1] -1

$vector
[1] -1 -1 -1  1  1

$sum
[1] -1

$vector
 [1]  1  1 -1  1 -1  1 -1  1 -1 -1

$sum
[1] 0

5. *Смешанное распределение.* Дано число `sz`. Сгенерируйте вектор размера `sz` по следующему алгоритму: чтобы получить очередное число вектора сначала бросается монетка. В одном случае нужно сгенерировать число из распределения $ \mathcal N(0, 1) $. Во втором случае из экспоненциального распределения с $ \lambda = 1 $.

In [14]:
task1_5 <- function(sz) {
    ifelse(runif(sz) < 0.5, rnorm(sz), rexp(sz, rate = 1))
}

In [30]:
set.seed(42)
task1_5(0)
task1_5(1)
task1_5(5)
task1_5(10)

logical(0)

[1] 0.1983368

[1] 0.12066549 0.09614656 0.05714136 1.55489555 0.30981574

 [1]  0.3512145  0.3926599 -0.1719174  0.7782936  1.8951935  0.3864096
 [7] -0.2572694 -1.7631631  0.4387117  4.1681296

## Задание №2
Создайте указанные матрицы. В этих задачах нельзя использовать циклы. И вы должны избежать ручного ввода элементов матрицы, вместо этого используйте возможности R по конструированию матриц. Т. е., например, если вас попросили создать матрицу $ 10 \times 10 $, не перечисляейте в решении все 100 элементов этой матрицы. Представьте, что вас просят на самом деле создавать матрицы $ 1000 \times 1000 $. Маленькие матрицы в условии нужны для того, чтобы вам было проще отладить свою программу, увидев матрицы на экране целиком.

1. Создайте матрицу $ n \times n $, у которой в каждой клетке стоит 0 или 1 в шахматном порядке. e.g.: $ n = 5 $
$$
\begin{pmatrix}
    0 & 1 & 0 & 1 & 0 \\
    1 & 0 & 1 & 0 & 1 \\
    0 & 1 & 0 & 1 & 0 \\
  	1 & 0 & 1 & 0 & 1 \\
  	0 & 1 & 0 & 1 & 0
\end{pmatrix}
$$

In [87]:
task2_1 <- function(n) {
    outer(1:n, 1:n, `+`) %% 2
}

In [88]:
task2_1(1)
task2_1(2)
task2_1(3)
task2_1(4)
task2_1(5)

     [,1]
[1,] 0

     [,1] [,2]
[1,] 0    1
[2,] 1    0

     [,1] [,2] [,3]
[1,] 0    1    0
[2,] 1    0    1
[3,] 0    1    0

     [,1] [,2] [,3] [,4]
[1,] 0    1    0    1
[2,] 1    0    1    0
[3,] 0    1    0    1
[4,] 1    0    1    0

     [,1] [,2] [,3] [,4] [,5]
[1,] 0    1    0    1    0
[2,] 1    0    1    0    1
[3,] 0    1    0    1    0
[4,] 1    0    1    0    1
[5,] 0    1    0    1    0

2. Даны натуральные числа $ n $ и $ m $. Сгенерируйте матрицу размера $ n \times m $, где первый столбец состоит из единиц, второй – из двоек, третий – из троек и т.д. Последний столбец содержит в себе значения $ m $.

In [89]:
task2_2 <- function(n, m) {
    matrix(1:m, nrow = n, ncol = m, byrow = TRUE)
}

In [90]:
task2_2(3, 4)
task2_2(1, 3)
task2_2(3, 1)

     [,1] [,2] [,3] [,4]
[1,] 1    2    3    4
[2,] 1    2    3    4
[3,] 1    2    3    4

     [,1] [,2] [,3]
[1,] 1    2    3

     [,1]
[1,] 1
[2,] 1
[3,] 1

3. Создайте матрицу $ n \times n $ с подряд идущими числами от 1 до $ n^2 $. Пример для $ n = 10 $:
$$
\begin{pmatrix}
  	1 & 2 & 3 & 4 & 5 & 6 & 7 & 8 & 9 & 10 \\
  	11 & 12 & 13 & 14 & 15 & 16 & 17 & 18 & 19 & 20 \\
  	21 & 22 & 23 & 24 & 25 & 26 & 27 & 28 & 29 & 30 \\
  	\cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots & \cdots \\
  	91 & 92 & 93 & 94 & 95 & 96 & 97 & 98 & 99 & 100
\end{pmatrix}
$$

In [91]:
task2_3 <- function(n) {
    t(matrix(1:(n * n), nrow = n))
}

In [92]:
task2_3(1)
task2_3(2)
task2_3(5)
task2_3(10)

     [,1]
[1,] 1

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2] [,3] [,4] [,5]
[1,]  1    2    3    4    5
[2,]  6    7    8    9   10
[3,] 11   12   13   14   15
[4,] 16   17   18   19   20
[5,] 21   22   23   24   25

      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  1    2    3    4    5    6    7    8    9    10
 [2,] 11   12   13   14   15   16   17   18   19    20
 [3,] 21   22   23   24   25   26   27   28   29    30
 [4,] 31   32   33   34   35   36   37   38   39    40
 [5,] 41   42   43   44   45   46   47   48   49    50
 [6,] 51   52   53   54   55   56   57   58   59    60
 [7,] 61   62   63   64   65   66   67   68   69    70
 [8,] 71   72   73   74   75   76   77   78   79    80
 [9,] 81   82   83   84   85   86   87   88   89    90
[10,] 91   92   93   94   95   96   97   98   99   100

4. Даны числа $ n $, $ a $, $ b $. Создайте матрицу размера $ n \times n $, у которой на главной диагонали стоят числа $ a $, а строго над и под главной диагональю стоят числа $ b $. Остальные числа матрицы – нули. Пример матрицы для $ n = 4 $, $ a = 1 $, $ b = 2 $:
$$
\begin{pmatrix}
  	1 & 2 & 0 & 0 \\
  	2 & 1 & 2 & 0 \\
  	0 & 2 & 1 & 2 \\
  	0 & 0 & 2 & 1
\end{pmatrix}
$$

In [93]:
task2_4 <- function(n, a, b) {
    M <- matrix(0, n, n)
    diag(M) <- a
    M[abs(row(M) - col(M)) == 1] <- b
    M
}

In [94]:
task2_4(1, 5, 7)
task2_4(2, 1, 2)
task2_4(4, 1, 2)
task2_4(5, 3, 9)

     [,1]
[1,] 5

     [,1] [,2]
[1,] 1    2
[2,] 2    1

     [,1] [,2] [,3] [,4]
[1,] 1    2    0    0
[2,] 2    1    2    0
[3,] 0    2    1    2
[4,] 0    0    2    1

     [,1] [,2] [,3] [,4] [,5]
[1,] 3    9    0    0    0
[2,] 9    3    9    0    0
[3,] 0    9    3    9    0
[4,] 0    0    9    3    9
[5,] 0    0    0    9    3

5. Дано натуральное число $ n $. Создайте следующую матрицу размера $ n \times n $: на главной диагонали матрицы чередуются 1 и 2. Дальше от каждой клетки главной диагонали направо и вниз расставляется то же числа, что и в самой этой клетке. Пример для $ n = 5 $:
$$
\begin{pmatrix}
  	1 & 1 & 1 & 1 & 1 \\
  	1 & 2 & 2 & 2 & 2 \\
  	1 & 2 & 1 & 1 & 1 \\
  	1 & 2 & 1 & 2 & 2 \\
  	1 & 2 & 1 & 2 & 1
\end{pmatrix}
$$

In [95]:
task2_5 <- function(n) {
    M <- matrix(1, n, n)
    M[pmin(row(M), col(M)) %% 2 == 0] <- 2
    M
}

In [96]:
task2_5(1)
task2_5(2)
task2_5(3)
task2_5(4)
task2_5(5)

     [,1]
[1,] 1

     [,1] [,2]
[1,] 1    1
[2,] 1    2

     [,1] [,2] [,3]
[1,] 1    1    1
[2,] 1    2    2
[3,] 1    2    1

     [,1] [,2] [,3] [,4]
[1,] 1    1    1    1
[2,] 1    2    2    2
[3,] 1    2    1    1
[4,] 1    2    1    2

     [,1] [,2] [,3] [,4] [,5]
[1,] 1    1    1    1    1
[2,] 1    2    2    2    2
[3,] 1    2    1    1    1
[4,] 1    2    1    2    2
[5,] 1    2    1    2    1

Кстати, а какой определитель у этой матрицы? А почему? Ответ укажите ниже.

Пусть $d_k: d_k = 1$, если k нечетное, и $d_k = 2$, если k четное

Тогда формула клетки матрицы: $a_{i, j} = d_{min(i,j)}$

При $j < i$ имеем что $j <= i - 1 < i$ тогда $min(i, j) = j = min(i−1, j)$

Значит, $a_{i,j} = d_j = a_{i-1,j}$ — клетки строк i и i−1 в этом столбце совпадают. Их разность равна нулю.

Это верно для всех j = 1, 2, …, i−1. Поэтому при вычитании $R_i − R_{i−1}$ для i = n, ..., 2 все эти позиции обнуляются.

Тогда после приведения матрицы к верхнетреугольному виду путем вычитания $R_i − R_{i−1}$ для i = n, ..., 2 получаем верхнетреугольную матрицу, у которой на диагонали $a'_{11} = 1$, а для i ≥ 2: $a'_{ii} = d_i − d_{i−1}$, что дает 1 при четном i и −1 при нечетном i ≥ 3

Значит диагональ: 1, 1, −1, 1, −1, ...

Поскольку определитель верхнетреугольной матрицы равен произведению элементов на главной диагонали получаем следующую формулу:
$$det⁡M_n=1⋅1⋅(−1)⋅1⋅(−1)⋯=(−1)^{⌊(n−1)/2⌋}$$

То есть $detM_n$ принимает значения 1, 1, −1, −1, 1, 1, … с периодом 4.

## Задание №3
В данных задачах **запрещено использовать циклы!**

1. Дана матрица с четным числом строк. Поменяйте местами верхнюю половину строк матрицы и нижнюю половину.

In [57]:
task3_1 <- function(M) {
    n <- nrow(M)
    half <- n / 2
    M[c((half + 1):n, 1:half), , drop = FALSE]
}

In [64]:
M1 <- matrix(1:4, nrow = 2, byrow = TRUE)
M1
task3_1(M1)
M2 <- matrix(11:18, nrow = 4, byrow = TRUE)
task3_1(M2)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 3    4
[2,] 1    2

     [,1] [,2]
[1,] 15   16
[2,] 17   18
[3,] 11   12
[4,] 13   14

2. Дан вектор из целых чисел `x`, число `k` и матрица `A` чётного размера. Реализуйте функцию, которая возвращает следующие **два объекта**:
  * Матрицу `B`: необходимо поделить матрицу `A` пополам по вертикали и горизонтали и получить матрицу, соответствующую верхнему левому квадрату. Затем необходимо увеличить все нечетные числа полученной матрицы в два раза.
  * Вектор `y`: данный вектор содержит только те числа вектора `x`, которые делятся на `k`.

In [65]:
task3_2 <- function(x, k, A) {
    n <- nrow(A)
    m <- ncol(A)
    B <- A[1:(n / 2), 1:(m / 2), drop = FALSE]
    B[B %% 2 == 1] <- B[B %% 2 == 1] * 2
    y <- x[x %% k == 0]
    list(B = B, y = y)
}

In [69]:
A1 = matrix(1:16, nrow = 4, byrow = TRUE)
A1
task3_2(c(2, 4, 6, 7, 9), 3, A1)
A2 = matrix(1, nrow = 2, ncol = 2)
A2
task3_2(c(1, 2, 3), 1, A2)

     [,1] [,2] [,3] [,4]
[1,]  1    2    3    4
[2,]  5    6    7    8
[3,]  9   10   11   12
[4,] 13   14   15   16

$B
     [,1] [,2]
[1,]    2    2
[2,]   10    6

$y
[1] 6 9

     [,1] [,2]
[1,] 1    1
[2,] 1    1

$B
     [,1]
[1,]    2

$y
[1] 1 2 3

3. Сделайте две функции:
  * `filter_multiples(a, k)` – удаляет из вектора `a` все числа, которые строго больше `k` и делятся на `k`;
  * `sieve(n)` – решето Эратосфена. Требуется вернуть вектор из простых чисел от 1 до `n`. Для этого создайте вектор всех целых чисел от 2 до `n`. С помощью предыдущей функции `filter_multiples` удалите сначала всё, что больше 2 и делится на 2. Потом всё, что больше 3 и делится на 3, потом все, что больше 5 (мы пропускаем 4, потому что оно уже было удалено на первом шаге) и делится на 5, и т.д. За подробностями смотрите, что такое [решето Эратосфена](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes).

In [ ]:
filter_multiples <- function(a, k) {
    a[!(a > k & a %% k == 0)]
}

sieve <- function(n) {
    if (n < 2) return(integer(0))
    nums <- 2:n
    sieve_rec <- function(v) {
        if (length(v) == 0) return(integer(0))
        p <- v[1]
        rest <- filter_multiples(v[-1], p)
        c(p, sieve_rec(rest))
    }
    sieve_rec(nums)
}

In [ ]:
filter_multiples(c(2, 4, 6, 7, 9, 10, 12), 3)   # 2 4 7 10
filter_multiples(c(1, 2, 4, 5), 3)              # 1 2 4 5
filter_multiples(c(5, 10, 15, 20), 5)           # 5

[1]  2  4  7 10

[1] 1 2 4 5

[1] 5

In [ ]:
sieve(1)    # ничего
sieve(2)    # 2
sieve(10)   # 2 3 5 7
sieve(30)   # 2 3 5 7 11 13 17 19 23 29
sieve(50)   # 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47

integer(0)

[1] 2

[1] 2 3 5 7

 [1]  2  3  5  7 11 13 17 19 23 29

 [1]  2  3  5  7 11 13 17 19 23 29 31 37 41 43 47

4. Дан столбец $ x $. Вернуть квадратную матрицу такого же размера, которая в $ i $-ой строке и $ j $-ом столбце содержит разность $ x_i - x_j $.

In [73]:
task3_4 <- function(x) {
    outer(x, x, "-")
}

In [74]:
task3_4(c(1, 2, 3))
task3_4(1:5)

     [,1] [,2] [,3]
[1,] 0    -1   -2
[2,] 1     0   -1
[3,] 2     1    0

     [,1] [,2] [,3] [,4] [,5]
[1,] 0    -1   -2   -3   -4
[2,] 1     0   -1   -2   -3
[3,] 2     1    0   -1   -2
[4,] 3     2    1    0   -1
[5,] 4     3    2    1    0

5. Дана матрица-строка, например, `a <- c(1, 2, -2, 4)` и число `x`, например 1. Строка `a` задает коэффициенты многочлена, начиная с младшего, т.е. она соответствует многочлену $ 1 + 2x - 2x^2 + 4x^3 $. Посчитайте значение многочлена в точке `x`. Для приведенного примера ответ будет 5. Т.е. необходимо написать выражение через `a` и `x`, которое считает значение многочлена `a` в точке `x`.

In [75]:
task3_5 <- function(a, x) {
    sum(a * x^(seq_along(a) - 1))
}

In [76]:
task3_5(c(1, 2, -2, 4), 1)   # 5
task3_5(c(1, 2, -2, 4), 2)   # 29
task3_5(c(7, 3, 5), 0)       # 7
task3_5(c(42), 100)          # 42
task3_5(c(1, 2, 3, 4), 1)    # 10

[1] 5

[1] 29

[1] 7

[1] 42

[1] 10